// Generated by gencpp from file ObservationService/ObservationRequest.msg
// DO NOT EDIT!


#ifndef OBSERVATIONSERVICE_MESSAGE_OBSERVATIONREQUEST_H
#define OBSERVATIONSERVICE_MESSAGE_OBSERVATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ObservationService
{
template <class ContainerAllocator>
struct ObservationRequest_
{
  typedef ObservationRequest_<ContainerAllocator> Type;

  ObservationRequest_()
    : state(0)
    , action(0)  {
    }
  ObservationRequest_(const ContainerAllocator& _alloc)
    : state(0)
    , action(0)  {
  (void)_alloc;
    }



   typedef int64_t _state_type;
  _state_type state;

   typedef int64_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::ObservationService::ObservationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ObservationService::ObservationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ObservationRequest_

typedef ::ObservationService::ObservationRequest_<std::allocator<void> > ObservationRequest;

typedef boost::shared_ptr< ::ObservationService::ObservationRequest > ObservationRequestPtr;
typedef boost::shared_ptr< ::ObservationService::ObservationRequest const> ObservationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ObservationService::ObservationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ObservationService::ObservationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ObservationService::ObservationRequest_<ContainerAllocator1> & lhs, const ::ObservationService::ObservationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.action == rhs.action;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ObservationService::ObservationRequest_<ContainerAllocator1> & lhs, const ::ObservationService::ObservationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ObservationService

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ObservationService::ObservationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ObservationService::ObservationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ObservationService::ObservationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ObservationService::ObservationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ObservationService::ObservationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ObservationService::ObservationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ObservationService::ObservationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "259bca38d4fc8628fe2040c8f9f63bed";
  }

  static const char* value(const ::ObservationService::ObservationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x259bca38d4fc8628ULL;
  static const uint64_t static_value2 = 0xfe2040c8f9f63bedULL;
};

template<class ContainerAllocator>
struct DataType< ::ObservationService::ObservationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ObservationService/ObservationRequest";
  }

  static const char* value(const ::ObservationService::ObservationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ObservationService::ObservationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 state\n"
"int64 action\n"
;
  }

  static const char* value(const ::ObservationService::ObservationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ObservationService::ObservationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObservationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ObservationService::ObservationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ObservationService::ObservationRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
    s << indent << "action: ";
    Printer<int64_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OBSERVATIONSERVICE_MESSAGE_OBSERVATIONREQUEST_H
